
import { Language } from './types';

export interface WordData {
  category: string;
  words: Record<Language, string>;
}

export const WORD_BANK: WordData[] = [
  // 1. Daily Objects (CAT_OBJECTS)
  { category: "CAT_OBJECTS", words: { fa: "لیوان", en: "Glass", nl: "Glas", de: "Glas", fr: "Verre", ar: "كأس", tr: "Bardak", pl: "Szklanka", uk: "Склянка" } },
  { category: "CAT_OBJECTS", words: { fa: "بشقاب", en: "Plate", nl: "Bord", de: "Teller", fr: "Assiette", ar: "صحن", tr: "Tabak", pl: "Talerz", uk: "Тарілка" } },
  { category: "CAT_OBJECTS", words: { fa: "قاشق", en: "Spoon", nl: "Lepel", de: "Löffel", fr: "Cuillère", ar: "ملعقة", tr: "Kaşık", pl: "Łyżka", uk: "Ложка" } },
  { category: "CAT_OBJECTS", words: { fa: "چنگال", en: "Fork", nl: "Vork", de: "Gabel", fr: "Fourchette", ar: "شوكة", tr: "Çatal", pl: "Widelec", uk: "Виделка" } },
  { category: "CAT_OBJECTS", words: { fa: "چاقو", en: "Knife", nl: "Mes", de: "Messer", fr: "Couteau", ar: "سكين", tr: "Bıçak", pl: "Nóż", uk: "Ніж" } },
  { category: "CAT_OBJECTS", words: { fa: "قابلمه", en: "Pot", nl: "Pan", de: "Topf", fr: "Marmite", ar: "قدر", tr: "Tencere", pl: "Garnek", uk: "Каструля" } },
  { category: "CAT_OBJECTS", words: { fa: "ماهیتابه", en: "Frying Pan", nl: "Koekenpan", de: "Pfanne", fr: "Poêle", ar: "مقلاة", tr: "Tava", pl: "Patelnia", uk: "Сковорідка" } },
  { category: "CAT_OBJECTS", words: { fa: "یخچال", en: "Fridge", nl: "Koelkast", de: "Kühlschrank", fr: "Frigo", ar: "ثلاجة", tr: "Buzdolabı", pl: "Lodówka", uk: "Холодильник" } },
  { category: "CAT_OBJECTS", words: { fa: "فریزر", en: "Freezer", nl: "Vriezer", de: "Gefrierschrank", fr: "Congélateur", ar: "مجمد", tr: "Dondurucu", pl: "Zamrażarka", uk: "Морозилка" } },
  { category: "CAT_OBJECTS", words: { fa: "اجاق", en: "Stove", nl: "Fornuis", de: "Herd", fr: "Cuisinière", ar: "موقد", tr: "Ocak", pl: "Kuchenka", uk: "Плита" } },
  { category: "CAT_OBJECTS", words: { fa: "فر", en: "Oven", nl: "Oven", de: "Ofen", fr: "Four", ar: "فرن", tr: "Fırın", pl: "Piekarnik", uk: "Духовка" } },
  { category: "CAT_OBJECTS", words: { fa: "مایکروویو", en: "Microwave", nl: "Magnetron", de: "Mikrowelle", fr: "Micro-ondes", ar: "مايكرويف", tr: "Mikrodalga", pl: "Mikrofalówka", uk: "Мікрохвильовка" } },
  { category: "CAT_OBJECTS", words: { fa: "سماور", en: "Samovar", nl: "Samovar", de: "Samowar", fr: "Samovar", ar: "سموار", tr: "Semaver", pl: "Samowar", uk: "Самовар" } },
  { category: "CAT_OBJECTS", words: { fa: "کتری", en: "Kettle", nl: "Waterkoker", de: "Wasserkocher", fr: "Bouilloire", ar: "غلاية", tr: "Çaydanlık", pl: "Czajnik", uk: "Чайник" } },
  { category: "CAT_OBJECTS", words: { fa: "قهوه‌ساز", en: "Coffee Maker", nl: "Koffiezetapparaat", de: "Kaffeemaschine", fr: "Cafetière", ar: "ماكينة قهوة", tr: "Kahve makinesi", pl: "Ekspres do kawy", uk: "Кавоварка" } },
  { category: "CAT_OBJECTS", words: { fa: "فنجان", en: "Cup", nl: "Kopje", de: "Tasse", fr: "Tassette", ar: "فنجان", tr: "Fincan", pl: "Filiżanka", uk: "Філіжанка" } },
  { category: "CAT_OBJECTS", words: { fa: "لیوان‌دسته‌دار", en: "Mug", nl: "Mok", de: "Becher", fr: "Mug", ar: "كوب", tr: "Kupa", pl: "Kubek", uk: "Кухоль" } },
  { category: "CAT_OBJECTS", words: { fa: "بطری", en: "Bottle", nl: "Fles", de: "Flasche", fr: "Bouteille", ar: "زجاجة", tr: "Şişe", pl: "Butelka", uk: "Пляшка" } },
  { category: "CAT_OBJECTS", words: { fa: "قمقمه", en: "Flask", nl: "Veldles", de: "Feldflasche", fr: "Gourde", ar: "زمزمية", tr: "Matara", pl: "Manierka", uk: "Фляга" } },
  { category: "CAT_OBJECTS", words: { fa: "سطل", en: "Bucket", nl: "Emmer", de: "Eimer", fr: "Seau", ar: "دلو", tr: "Kova", pl: "Wiadro", uk: "Відро" } },
  { category: "CAT_OBJECTS", words: { fa: "جارو", en: "Broom", nl: "Bezem", de: "Besen", fr: "Balai", ar: "مكنسة", tr: "Süpürge", pl: "Miotła", uk: "Мітла" } },
  { category: "CAT_OBJECTS", words: { fa: "خاک‌انداز", en: "Dustpan", nl: "Stoffer en blik", de: "Kehrschaufel", fr: "Pelle à poussière", ar: "جاروف", tr: "Faraş", pl: "Szufla", uk: "Совок" } },
  { category: "CAT_OBJECTS", words: { fa: "تی", en: "Mop", nl: "Dweil", de: "Mopp", fr: "Serpillière", ar: "ممسحة", tr: "Paspas", pl: "Mop", uk: "Швабра" } },
  { category: "CAT_OBJECTS", words: { fa: "دستمال", en: "Tissue", nl: "Zakdoek", de: "Taschentuch", fr: "Mouchoir", ar: "منديل", tr: "Mendil", pl: "Chusteczka", uk: "Серветка" } },
  { category: "CAT_OBJECTS", words: { fa: "اسکاچ", en: "Scrubber", nl: "Spons", de: "Schwamm", fr: "Éponge", ar: "إسفنجة", tr: "Sünger", pl: "Gąbka", uk: "Губка" } },
  { category: "CAT_OBJECTS", words: { fa: "شوینده", en: "Detergent", nl: "Wasmiddel", de: "Waschmittel", fr: "Détergent", ar: "منظف", tr: "Deterjan", pl: "Detergent", uk: "Миючий засіб" } },
  { category: "CAT_OBJECTS", words: { fa: "صابون", en: "Soap", nl: "Zeep", de: "Seife", fr: "Savon", ar: "صابون", tr: "Sabun", pl: "Mydło", uk: "Мило" } },
  { category: "CAT_OBJECTS", words: { fa: "شامپو", en: "Shampoo", nl: "Shampoo", de: "Shampoo", fr: "Shampooing", ar: "شامبو", tr: "Şampuan", pl: "Szampon", uk: "Шампунь" } },
  { category: "CAT_OBJECTS", words: { fa: "مسواک", en: "Toothbrush", nl: "Tandenborstel", de: "Zahnbürste", fr: "Brosse à dents", ar: "فرشاة أسنان", tr: "Diş fırçası", pl: "Szczoteczka", uk: "Зубна щітка" } },
  { category: "CAT_OBJECTS", words: { fa: "خمیردندان", en: "Toothpaste", nl: "Tandpasta", de: "Zahnpasta", fr: "Dentifrice", ar: "معجون أسنان", tr: "Diş macunu", pl: "Pasta do zębów", uk: "Зубна паста" } },
  { category: "CAT_OBJECTS", words: { fa: "حوله", en: "Towel", nl: "Handdoek", de: "Handtuch", fr: "Serviette", ar: "منشفة", tr: "Havlu", pl: "Ręcznik", uk: "Рушник" } },
  { category: "CAT_OBJECTS", words: { fa: "آینه", en: "Mirror", nl: "Spiegel", de: "Spiegel", fr: "Miroir", ar: "مرآة", tr: "Ayna", pl: "Lustro", uk: "Дзеркало" } },
  { category: "CAT_OBJECTS", words: { fa: "شانه", en: "Comb", nl: "Kam", de: "Kamm", fr: "Peigne", ar: "مشط", tr: "Tarak", pl: "Grzebień", uk: "Гребінець" } },
  { category: "CAT_OBJECTS", words: { fa: "سشوار", en: "Hairdryer", nl: "Föhn", de: "Föhn", fr: "Sèche-cheveux", ar: "مجفف شعر", tr: "Fön", pl: "Suszarka", uk: "Фен" } },
  { category: "CAT_OBJECTS", words: { fa: "ریش‌تراش", en: "Razor", nl: "Scheermes", de: "Rasierer", fr: "Rasoir", ar: "ماكينة حلاقة", tr: "Tıraş makinesi", pl: "Golarka", uk: "Бритва" } },
  { category: "CAT_OBJECTS", words: { fa: "کمد", en: "Closet", nl: "Kast", de: "Schrank", fr: "Armoire", ar: "خزانة", tr: "Dolap", pl: "Szafa", uk: "Шафа" } },
  { category: "CAT_OBJECTS", words: { fa: "کشو", en: "Drawer", nl: "Lade", de: "Schublade", fr: "Tiroir", ar: "درج", tr: "Çekmece", pl: "Szuflada", uk: "Шухляда" } },
  { category: "CAT_OBJECTS", words: { fa: "میز", en: "Table", nl: "Tafel", de: "Tisch", fr: "Table", ar: "طاولة", tr: "Masa", pl: "Stół", uk: "Стіл" } },
  { category: "CAT_OBJECTS", words: { fa: "صندلی", en: "Chair", nl: "Stoel", de: "Stuhl", fr: "Chaise", ar: "كرسي", tr: "Sandalye", pl: "Krzesło", uk: "Стілець" } },
  { category: "CAT_OBJECTS", words: { fa: "مبل", en: "Sofa", nl: "Bank", de: "Sofa", fr: "Canapé", ar: "أريكة", tr: "Kanepe", pl: "Kanapa", uk: "Диван" } },
  { category: "CAT_OBJECTS", words: { fa: "تخت", en: "Bed", nl: "Bed", de: "Bett", fr: "Lit", ar: "سرير", tr: "Yatak", pl: "Łóżko", uk: "Ліжко" } },
  { category: "CAT_OBJECTS", words: { fa: "بالش", en: "Pillow", nl: "Kussen", de: "Kissen", fr: "Oreiller", ar: "وسادة", tr: "Yastık", pl: "Poduszka", uk: "Подушка" } },
  { category: "CAT_OBJECTS", words: { fa: "پتو", en: "Blanket", nl: "Deken", de: "Decke", fr: "Couverture", ar: "بطانية", tr: "Battaniye", pl: "Koc", uk: "Ковдра" } },
  { category: "CAT_OBJECTS", words: { fa: "ملحفه", en: "Sheet", nl: "Laken", de: "Laken", fr: "Drap", ar: "ملاءة", tr: "Çarşaf", pl: "Prześcieradło", uk: "Простирадло" } },
  { category: "CAT_OBJECTS", words: { fa: "پرده", en: "Curtain", nl: "Gordijn", de: "Vorhang", fr: "Rideau", ar: "ستارة", tr: "Perde", pl: "Zasłona", uk: "Штора" } },
  { category: "CAT_OBJECTS", words: { fa: "فرش", en: "Carpet", nl: "Tapijt", de: "Teppich", fr: "Tapis", ar: "سجادة", tr: "Halı", pl: "Dywan", uk: "Килим" } },
  { category: "CAT_OBJECTS", words: { fa: "قالیچه", en: "Rug", nl: "Vloerkleed", de: "Läufer", fr: "Carpette", ar: "بساط", tr: "Kilim", pl: "Chodnik", uk: "Килимок" } },
  { category: "CAT_OBJECTS", words: { fa: "کفش", en: "Shoes", nl: "Schoenen", de: "Schuhe", fr: "Chaussures", ar: "حذاء", tr: "Ayakkabı", pl: "Buty", uk: "Взуття" } },
  { category: "CAT_OBJECTS", words: { fa: "دمپایی", en: "Slippers", nl: "Slippers", de: "Hausschuhe", fr: "Pantoufles", ar: "شبشب", tr: "Terlik", pl: "Kapcie", uk: "Тапочки" } },
  { category: "CAT_OBJECTS", words: { fa: "کتانی", en: "Sneakers", nl: "Sneakers", de: "Sneaker", fr: "Baskets", ar: "حذاء رياضي", tr: "Spor ayakkabı", pl: "Trampki", uk: "Кеди" } },
  { category: "CAT_OBJECTS", words: { fa: "جوراب", en: "Socks", nl: "Sokken", de: "Socken", fr: "Chaussettes", ar: "جوارب", tr: "Çorap", pl: "Skarpetki", uk: "Шкарпетки" } },
  { category: "CAT_OBJECTS", words: { fa: "کمربند", en: "Belt", nl: "Riem", de: "Gürtel", fr: "Ceinture", ar: "حزام", tr: "Kemer", pl: "Pasek", uk: "Ремінь" } },
  { category: "CAT_OBJECTS", words: { fa: "کیف", en: "Bag", nl: "Tas", de: "Tasche", fr: "Sac", ar: "حقيبة", tr: "Çanta", pl: "Torba", uk: "Сумка" } },
  { category: "CAT_OBJECTS", words: { fa: "کوله‌پشتی", en: "Backpack", nl: "Rugzak", de: "Rucksack", fr: "Sac à dos", ar: "حقيبة ظهر", tr: "Sırt çantası", pl: "Plecak", uk: "Рюкзак" } },
  { category: "CAT_OBJECTS", words: { fa: "چتر", en: "Umbrella", nl: "Paraplu", de: "Regenschirm", fr: "Parapluie", ar: "مظلة", tr: "Şemsiye", pl: "Parasol", uk: "Парасоля" } },
  { category: "CAT_OBJECTS", words: { fa: "عینک", en: "Glasses", nl: "Bril", de: "Brille", fr: "Lunettes", ar: "نظارات", tr: "Gözlük", pl: "Okulary", uk: "Окуляри" } },
  { category: "CAT_OBJECTS", words: { fa: "ساعت", en: "Watch", nl: "Horloge", de: "Uhr", fr: "Montre", ar: "ساعة", tr: "Saat", pl: "Zegarek", uk: "Годинник" } },
  { category: "CAT_OBJECTS", words: { fa: "تلفن", en: "Telephone", nl: "Telefoon", de: "Telefon", fr: "Téléphone", ar: "هاتف", tr: "Telefon", pl: "Telefon", uk: "Телефон" } },
  { category: "CAT_OBJECTS", words: { fa: "موبایل", en: "Mobile Phone", nl: "Mobiel", de: "Handy", fr: "Mobile", ar: "جوال", tr: "Cep telefonu", pl: "Komórka", uk: "Мобільний" } },
  { category: "CAT_OBJECTS", words: { fa: "شارژر", en: "Charger", nl: "Oplader", de: "Ladegerät", fr: "Chargeur", ar: "شاحن", tr: "Şarj aleti", pl: "Ładowarka", uk: "Зарядка" } },
  { category: "CAT_OBJECTS", words: { fa: "کابل", en: "Cable", nl: "Kabel", de: "Kabel", fr: "Câble", ar: "كابل", tr: "Kablo", pl: "Kabel", uk: "Кабель" } },
  { category: "CAT_OBJECTS", words: { fa: "پریز", en: "Socket", nl: "Stopcontact", de: "Steckdose", fr: "Prise", ar: "مقبس", tr: "Priz", pl: "Gniazdko", uk: "Розетка" } },
  { category: "CAT_OBJECTS", words: { fa: "کلید", en: "Key", nl: "Sleutel", de: "Schlüssel", fr: "Clé", ar: "مفتاح", tr: "Anahtar", pl: "Klucz", uk: "Ключ" } },
  { category: "CAT_OBJECTS", words: { fa: "قفل", en: "Lock", nl: "Slot", de: "Schloss", fr: "Serrure", ar: "قفل", tr: "Kilit", pl: "Zamek", uk: "Замок" } },
  { category: "CAT_OBJECTS", words: { fa: "در", en: "Door", nl: "Deur", de: "Tür", fr: "Porte", ar: "باب", tr: "Kapı", pl: "Drzwi", uk: "Двері" } },
  { category: "CAT_OBJECTS", words: { fa: "پنجره", en: "Window", nl: "Raam", de: "Fenster", fr: "Fenêtre", ar: "نافذة", tr: "Pencere", pl: "Okno", uk: "Вікно" } },
  { category: "CAT_OBJECTS", words: { fa: "دستگیره", en: "Handle", nl: "Handvat", de: "Griff", fr: "Poignée", ar: "مقبض", tr: "Kol", pl: "Klamka", uk: "Ручка" } },
  { category: "CAT_OBJECTS", words: { fa: "لامپ", en: "Bulb", nl: "Lamp", de: "Glühbirne", fr: "Ampoule", ar: "مصباح", tr: "Ampul", pl: "Żarówka", uk: "Лампочка" } },
  { category: "CAT_OBJECTS", words: { fa: "لوستر", en: "Chandelier", nl: "Kroonluchter", de: "Kronleuchter", fr: "Lustre", ar: "نجفة", tr: "Avize", pl: "Żyrandol", uk: "Люстра" } },
  { category: "CAT_OBJECTS", words: { fa: "آباژور", en: "Lamp Shade", nl: "Lampenkap", de: "Lampenschirm", fr: "Abat-jour", ar: "أباجورة", tr: "Abajur", pl: "Abażur", uk: "Абажур" } },
  { category: "CAT_OBJECTS", words: { fa: "تلویزیون", en: "Television", nl: "Televisie", de: "Fernseher", fr: "Télévision", ar: "تلفزيون", tr: "Televizyon", pl: "Telewizor", uk: "Телевізор" } },
  { category: "CAT_OBJECTS", words: { fa: "کنترل", en: "Remote", nl: "Afstandsbediening", de: "Fernbedienung", fr: "Télécommande", ar: "ريموت", tr: "Kumanda", pl: "Pilot", uk: "Пульт" } },
  { category: "CAT_OBJECTS", words: { fa: "رادیو", en: "Radio", nl: "Radio", de: "Radio", fr: "Radio", ar: "راديو", tr: "Radyo", pl: "Radio", uk: "Радіо" } },
  { category: "CAT_OBJECTS", words: { fa: "بلندگو", en: "Speaker", nl: "Luidspreker", de: "Lautsprecher", fr: "Haut-parleur", ar: "مكبر صوت", tr: "Hoparlör", pl: "Głośnik", uk: "Динамік" } },
  { category: "CAT_OBJECTS", words: { fa: "هدفون", en: "Headphones", nl: "Koptelefoon", de: "Kopfhörer", fr: "Casque", ar: "سماعات", tr: "Kulaklık", pl: "Słuchawki", uk: "Навушники" } },
  { category: "CAT_OBJECTS", words: { fa: "لپ‌تاپ", en: "Laptop", nl: "Laptop", de: "Laptop", fr: "Portable", ar: "لابتوب", tr: "Laptop", pl: "Laptop", uk: "Ноутбук" } },
  { category: "CAT_OBJECTS", words: { fa: "موس", en: "Mouse", nl: "Muis", de: "Maus", fr: "Souris", ar: "ماوس", tr: "Fare", pl: "Myszka", uk: "Мишка" } },
  { category: "CAT_OBJECTS", words: { fa: "کیبورد", en: "Keyboard", nl: "Toetsenbord", de: "Tastatur", fr: "Clavier", ar: "لوحة مفاتيح", tr: "Klavye", pl: "Klawiatura", uk: "Клавіатура" } },
  { category: "CAT_OBJECTS", words: { fa: "پرینتر", en: "Printer", nl: "Printer", de: "Drucker", fr: "Imprimante", ar: "طابعة", tr: "Yazıcı", pl: "Drukarka", uk: "Принтер" } },
  { category: "CAT_OBJECTS", words: { fa: "دفتر", en: "Notebook", nl: "Schrift", de: "Notizbuch", fr: "Cahier", ar: "دفتر", tr: "Defter", pl: "Zeszyt", uk: "Зошит" } },
  { category: "CAT_OBJECTS", words: { fa: "خودکار", en: "Pen", nl: "Pen", de: "Kuli", fr: "Stylo", ar: "قلم", tr: "Kalem", pl: "Długopis", uk: "Ручка" } },
  { category: "CAT_OBJECTS", words: { fa: "مداد", en: "Pencil", nl: "Potlood", de: "Bleistift", fr: "Crayon", ar: "مرسام", tr: "Kurşun kalem", pl: "Ołówek", uk: "Олівець" } },
  { category: "CAT_OBJECTS", words: { fa: "پاک‌کن", en: "Eraser", nl: "Gum", de: "Radiergummi", fr: "Gomme", ar: "ممحاة", tr: "Silgi", pl: "Gumka", uk: "Гумка" } },
  // Colors (Mapped to CAT_OBJECTS for volume)
  { category: "CAT_OBJECTS", words: { fa: "قرمز", en: "Red", nl: "Rood", de: "Rot", fr: "Rouge", ar: "أحمر", tr: "Kırmızı", pl: "Czerwony", uk: "Червоний" } },
  { category: "CAT_OBJECTS", words: { fa: "آبی", en: "Blue", nl: "Blauw", de: "Blau", fr: "Bleu", ar: "أزرق", tr: "Mavi", pl: "Niebieski", uk: "Синій" } },
  { category: "CAT_OBJECTS", words: { fa: "سبز", en: "Green", nl: "Groen", de: "Grün", fr: "Vert", ar: "أخضر", tr: "Yeşil", pl: "Zielony", uk: "Зелений" } },
  { category: "CAT_OBJECTS", words: { fa: "زرد", en: "Yellow", nl: "Geel", de: "Gelb", fr: "Jaune", ar: "أصفر", tr: "Sarı", pl: "Żółty", uk: "Жовтий" } },
  { category: "CAT_OBJECTS", words: { fa: "مشکی", en: "Black", nl: "Zwart", de: "Schwarz", fr: "Noir", ar: "أسود", tr: "Siyah", pl: "Czarny", uk: "Чорний" } },
  { category: "CAT_OBJECTS", words: { fa: "سفید", en: "White", nl: "Wit", de: "Weiß", fr: "Blanc", ar: "أبيض", tr: "Beyaz", pl: "Biały", uk: "Білий" } },
  // Family
  { category: "CAT_OBJECTS", words: { fa: "مادر", en: "Mother", nl: "Moeder", de: "Mutter", fr: "Mère", ar: "أم", tr: "Anne", pl: "Matka", uk: "Мати" } },
  { category: "CAT_OBJECTS", words: { fa: "پدر", en: "Father", nl: "Vader", de: "Vater", fr: "Père", ar: "أب", tr: "Baba", pl: "Ojciec", uk: "Батько" } },
  { category: "CAT_OBJECTS", words: { fa: "خواهر", en: "Sister", nl: "Zus", de: "Schwester", fr: "Sœur", ar: "أخت", tr: "Kız kardeş", pl: "Siostra", uk: "Сестра" } },
  { category: "CAT_OBJECTS", words: { fa: "برادر", en: "Brother", nl: "Broer", de: "Bruder", fr: "Frère", ar: "أخ", tr: "Erkek kardeş", pl: "Brat", uk: "Брат" } },

  // 2. Food & Drinks (CAT_FOOD)
  { category: "CAT_FOOD", words: { fa: "نان", en: "Bread", nl: "Brood", de: "Brot", fr: "Pain", ar: "خبز", tr: "Ekmek", pl: "Chleb", uk: "Хліб" } },
  { category: "CAT_FOOD", words: { fa: "برنج", en: "Rice", nl: "Rijst", de: "Reis", fr: "Riz", ar: "أرز", tr: "Pirinç", pl: "Ryż", uk: "Рис" } },
  { category: "CAT_FOOD", words: { fa: "ماکارونی", en: "Pasta", nl: "Pasta", de: "Pasta", fr: "Pâtes", ar: "معكرونة", tr: "Makarna", pl: "Makaron", uk: "Макарони" } },
  { category: "CAT_FOOD", words: { fa: "سیب‌زمینی", en: "Potato", nl: "Aardappel", de: "Kartoffel", fr: "Pomme de terre", ar: "بطاطس", tr: "Patates", pl: "Ziemniak", uk: "Картопля" } },
  { category: "CAT_FOOD", words: { fa: "گوجه", en: "Tomato", nl: "Tomaat", de: "Tomate", fr: "Tomate", ar: "طماطم", tr: "Domates", pl: "Pomidor", uk: "Помідор" } },
  { category: "CAT_FOOD", words: { fa: "خیار", en: "Cucumber", nl: "Komkommer", de: "Gurke", fr: "Concombre", ar: "خيار", tr: "Salatalık", pl: "Ogórek", uk: "Огірок" } },
  { category: "CAT_FOOD", words: { fa: "پیاز", en: "Onion", nl: "Ui", de: "Zwiebel", fr: "Oignon", ar: "بصل", tr: "Soğan", pl: "Cebula", uk: "Цибуля" } },
  { category: "CAT_FOOD", words: { fa: "سیر", en: "Garlic", nl: "Knoflook", de: "Knoblauch", fr: "Ail", ar: "ثوم", tr: "Sarımsak", pl: "Czosnek", uk: "Часник" } },
  { category: "CAT_FOOD", words: { fa: "هویج", en: "Carrot", nl: "Wortel", de: "Möhre", fr: "Carotte", ar: "جزر", tr: "Havuç", pl: "Marchew", uk: "Морква" } },
  { category: "CAT_FOOD", words: { fa: "کاهو", en: "Lettuce", nl: "Sla", de: "Salat", fr: "Laitue", ar: "خس", tr: "Marul", pl: "Sałata", uk: "Салат" } },
  { category: "CAT_FOOD", words: { fa: "کلم", en: "Cabbage", nl: "Kool", de: "Kohl", fr: "Chou", ar: "ملفوف", tr: "Lahana", pl: "Kapusta", uk: "Капуста" } },
  { category: "CAT_FOOD", words: { fa: "بادمجان", en: "Eggplant", nl: "Aubergine", de: "Aubergine", fr: "Aubergine", ar: "باذنجان", tr: "Patlıcan", pl: "Bakłażan", uk: "Баклажан" } },
  { category: "CAT_FOOD", words: { fa: "فلفل", en: "Pepper", nl: "Peper", de: "Pfeffer", fr: "Poivre", ar: "فلفل", tr: "Biber", pl: "Pieprz", uk: "Перець" } },
  { category: "CAT_FOOD", words: { fa: "قارچ", en: "Mushroom", nl: "Paddenstoel", de: "Pilz", fr: "Champignon", ar: "فطر", tr: "Mantar", pl: "Grzyb", uk: "Гриб" } },
  { category: "CAT_FOOD", words: { fa: "گوشت", en: "Meat", nl: "Vlees", de: "Fleisch", fr: "Viande", ar: "لحم", tr: "Et", pl: "Mięso", uk: "М'ясо" } },
  { category: "CAT_FOOD", words: { fa: "مرغ", en: "Chicken", nl: "Kip", de: "Huhn", fr: "Poulet", ar: "دجاج", tr: "Tavuk", pl: "Kurczak", uk: "Курка" } },
  { category: "CAT_FOOD", words: { fa: "ماهی", en: "Fish", nl: "Vis", de: "Fisch", fr: "Poisson", ar: "سمك", tr: "Balık", pl: "Ryba", uk: "Риба" } },
  { category: "CAT_FOOD", words: { fa: "تخم‌مرغ", en: "Egg", nl: "Ei", de: "Ei", fr: "Œuf", ar: "بيض", tr: "Yumurta", pl: "Jajko", uk: "Яйце" } },
  { category: "CAT_FOOD", words: { fa: "پنیر", en: "Cheese", nl: "Kaas", de: "Käse", fr: "Fromage", ar: "جبن", tr: "Peynir", pl: "Ser", uk: "Сир" } },
  { category: "CAT_FOOD", words: { fa: "ماست", en: "Yogurt", nl: "Yoghurt", de: "Joghurt", fr: "Yaourt", ar: "زبادي", tr: "Yoğurt", pl: "Jogurt", uk: "Йогурт" } },
  { category: "CAT_FOOD", words: { fa: "کره", en: "Butter", nl: "Boter", de: "Butter", fr: "Beurre", ar: "زبدة", tr: "Tereyağı", pl: "Masło", uk: "Масло" } },
  { category: "CAT_FOOD", words: { fa: "خامه", en: "Cream", nl: "Room", de: "Sahne", fr: "Crème", ar: "قشطة", tr: "Krema", pl: "Śmietana", uk: "Вершки" } },
  { category: "CAT_FOOD", words: { fa: "شیر", en: "Milk", nl: "Melk", de: "Milch", fr: "Lait", ar: "حليب", tr: "Süt", pl: "Mleko", uk: "Молоко" } },
  { category: "CAT_FOOD", words: { fa: "بستنی", en: "Ice Cream", nl: "IJs", de: "Eis", fr: "Glace", ar: "بوظة", tr: "Dondurma", pl: "Lody", uk: "Морозиво" } },
  { category: "CAT_FOOD", words: { fa: "کیک", en: "Cake", nl: "Taart", de: "Kuchen", fr: "Gâteau", ar: "كعك", tr: "Pasta", pl: "Ciasto", uk: "Торт" } },
  { category: "CAT_FOOD", words: { fa: "شکلات", en: "Chocolate", nl: "Chocolade", de: "Schokolade", fr: "Chocolat", ar: "شوكولاتة", tr: "Çikolata", pl: "Czekolada", uk: "Шоколад" } },
  { category: "CAT_FOOD", words: { fa: "موز", en: "Banana", nl: "Banaan", de: "Banane", fr: "Banane", ar: "موز", tr: "Muz", pl: "Banan", uk: "Банан" } },
  { category: "CAT_FOOD", words: { fa: "سیب", en: "Apple", nl: "Appel", de: "Apfel", fr: "Pomme", ar: "تفاحة", tr: "Elma", pl: "Jabłko", uk: "Яблуко" } },
  { category: "CAT_FOOD", words: { fa: "پرتقال", en: "Orange", nl: "Sinaasappel", de: "Orange", fr: "Orange", ar: "برتقال", tr: "Portakal", pl: "Pomarańcza", uk: "Апельсин" } },
  { category: "CAT_FOOD", words: { fa: "انار", en: "Pomegranate", nl: "Granaatappel", de: "Granatapfel", fr: "Grenade", ar: "رمان", tr: "Nar", pl: "Granat", uk: "Гранат" } },
  { category: "CAT_FOOD", words: { fa: "انگور", en: "Grape", nl: "Druif", de: "Traube", fr: "Raisin", ar: "عنب", tr: "Üzüm", pl: "Winogrono", uk: "Виноград" } },
  { category: "CAT_FOOD", words: { fa: "هندوانه", en: "Watermelon", nl: "Watermeloen", de: "Wassermelone", fr: "Pastèque", ar: "بطيخ", tr: "Karpuz", pl: "Arbuz", uk: "Кавун" } },
  { category: "CAT_FOOD", words: { fa: "قهوه", en: "Coffee", nl: "Koffie", de: "Kaffee", fr: "Café", ar: "قهوة", tr: "Kahve", pl: "Kawa", uk: "Кава" } },
  { category: "CAT_FOOD", words: { fa: "چای", en: "Tea", nl: "Thee", de: "Tee", fr: "Thé", ar: "شاي", tr: "Çay", pl: "Herbata", uk: "Чай" } },
  { category: "CAT_FOOD", words: { fa: "پیتزا", en: "Pizza", nl: "Pizza", de: "Pizza", fr: "Pizza", ar: "بيتزا", tr: "Pizza", pl: "Pizza", uk: "Піца" } },
  { category: "CAT_FOOD", words: { fa: "همبرگر", en: "Hamburger", nl: "Hamburger", de: "Hamburger", fr: "Hamburger", ar: "همبرجر", tr: "Hamburger", pl: "Hamburger", uk: "Гамбургер" } },
  { category: "CAT_FOOD", words: { fa: "ساندویچ", en: "Sandwich", nl: "Sandwich", de: "Sandwich", fr: "Sandwich", ar: "ساندويتش", tr: "Sandviç", pl: "Kanapka", uk: "Сендвіч" } },
  { category: "CAT_FOOD", words: { fa: "کباب", en: "Kebab", nl: "Kebab", de: "Kebab", fr: "Kebab", ar: "كباب", tr: "Kebap", pl: "Kebab", uk: "Кебаб" } },

  // 3. Animals (CAT_ANIMALS)
  { category: "CAT_ANIMALS", words: { fa: "سگ", en: "Dog", nl: "Hond", de: "Hund", fr: "Chien", ar: "كلب", tr: "Köpek", pl: "Pies", uk: "Собака" } },
  { category: "CAT_ANIMALS", words: { fa: "گربه", en: "Cat", nl: "Kat", de: "Katze", fr: "Chat", ar: "قطة", tr: "Kedi", pl: "Kot", uk: "Кіт" } },
  { category: "CAT_ANIMALS", words: { fa: "اسب", en: "Horse", nl: "Paard", de: "Pferd", fr: "Cheval", ar: "حصان", tr: "At", pl: "Koń", uk: "Кінь" } },
  { category: "CAT_ANIMALS", words: { fa: "گاو", en: "Cow", nl: "Koe", de: "Kuh", fr: "Vache", ar: "بقرة", tr: "İnek", pl: "Krowa", uk: "Корова" } },
  { category: "CAT_ANIMALS", words: { fa: "گوسفند", en: "Sheep", nl: "Schaap", de: "Schaf", fr: "Mouton", ar: "خروف", tr: "Koyun", pl: "Owca", uk: "Вівця" } },
  { category: "CAT_ANIMALS", words: { fa: "بز", en: "Goat", nl: "Geit", de: "Ziege", fr: "Chèvre", ar: "ماعز", tr: "Keçi", pl: "Koza", uk: "Коза" } },
  { category: "CAT_ANIMALS", words: { fa: "شتر", en: "Camel", nl: "Kameel", de: "Kamel", fr: "Chameau", ar: "جمل", tr: "Deve", pl: "Wielbłąd", uk: "Верблюд" } },
  { category: "CAT_ANIMALS", words: { fa: "خرگوش", en: "Rabbit", nl: "Konijn", de: "Hase", fr: "Lapin", ar: "أرنب", tr: "Tavşan", pl: "Królik", uk: "Кролик" } },
  { category: "CAT_ANIMALS", words: { fa: "موش", en: "Mouse", nl: "Muis", de: "Maus", fr: "Souris", ar: "فأر", tr: "Fare", pl: "Mysz", uk: "Миша" } },
  { category: "CAT_ANIMALS", words: { fa: "سنجاب", en: "Squirrel", nl: "Eekhoorn", de: "Eichhörnchen", fr: "Écureuil", ar: "سنجاب", tr: "Sincap", pl: "Wiewiórka", uk: "Білка" } },
  { category: "CAT_ANIMALS", words: { fa: "خرس", en: "Bear", nl: "Beer", de: "Bär", fr: "Ours", ar: "دب", tr: "Ayı", pl: "Niedźwiedź", uk: "Ведмідь" } },
  { category: "CAT_ANIMALS", words: { fa: "گرگ", en: "Wolf", nl: "Wolf", de: "Wolf", fr: "Loup", ar: "ذئب", tr: "Kurt", pl: "Wilk", uk: "Вовк" } },
  { category: "CAT_ANIMALS", words: { fa: "روباه", en: "Fox", nl: "Vos", de: "Fuchs", fr: "Renard", ar: "ثعلب", tr: "Tilki", pl: "Lis", uk: "Лисиця" } },
  { category: "CAT_ANIMALS", words: { fa: "شیر", en: "Lion", nl: "Leeuw", de: "Löwe", fr: "Lion", ar: "أسد", tr: "Aslan", pl: "Lew", uk: "Лев" } },
  { category: "CAT_ANIMALS", words: { fa: "ببر", en: "Tiger", nl: "Tijger", de: "Tiger", fr: "Tigre", ar: "نمر", tr: "Kaplan", pl: "Tygrys", uk: "Тигр" } },
  { category: "CAT_ANIMALS", words: { fa: "پلنگ", en: "Leopard", nl: "Luipaard", de: "Leopard", fr: "Léopard", ar: "فهد", tr: "Pars", pl: "Lampart", uk: "Леопард" } },
  { category: "CAT_ANIMALS", words: { fa: "فیل", en: "Elephant", nl: "Olifant", de: "Elefant", fr: "Éléphant", ar: "فيل", tr: "Fil", pl: "Słoń", uk: "Слон" } },
  { category: "CAT_ANIMALS", words: { fa: "زرافه", en: "Giraffe", nl: "Giraffe", de: "Giraffe", fr: "Girafe", ar: "زرافة", tr: "Zürafa", pl: "Żyrafa", uk: "Жирафа" } },
  { category: "CAT_ANIMALS", words: { fa: "گورخر", en: "Zebra", nl: "Zebra", de: "Zebra", fr: "Zèbre", ar: "حمار وحشي", tr: "Zebra", pl: "Zebra", uk: "Зебра" } },
  { category: "CAT_ANIMALS", words: { fa: "میمون", en: "Monkey", nl: "Aap", de: "Affe", fr: "Singe", ar: "قرد", tr: "Maymun", pl: "Małpa", uk: "Мавпа" } },
  { category: "CAT_ANIMALS", words: { fa: "تمساح", en: "Crocodile", nl: "Krokodil", de: "Krokodil", fr: "Crocodile", ar: "تمساح", tr: "Timsah", pl: "Krokodyl", uk: "Крокодил" } },
  { category: "CAT_ANIMALS", words: { fa: "مار", en: "Snake", nl: "Slang", de: "Schlange", fr: "Serpent", ar: "ثعبان", tr: "Yılan", pl: "Wąż", uk: "Змія" } },
  { category: "CAT_ANIMALS", words: { fa: "لاک‌پشت", en: "Turtle", nl: "Schildpad", de: "Schildkröte", fr: "Tortue", ar: "سلحفاة", tr: "Kaplumbağa", pl: "Żółw", uk: "Черепаха" } },
  { category: "CAT_ANIMALS", words: { fa: "قورباغه", en: "Frog", nl: "Kikker", de: "Frosch", fr: "Grenouille", ar: "ضفدع", tr: "Kurbağa", pl: "Żaba", uk: "Жаба" } },
  { category: "CAT_ANIMALS", words: { fa: "کوسه", en: "Shark", nl: "Haai", de: "Hai", fr: "Requin", ar: "قرش", tr: "Köpekbalığı", pl: "Rekin", uk: "Акула" } },
  { category: "CAT_ANIMALS", words: { fa: "دلفین", en: "Dolphin", nl: "Dolfijn", de: "Delfin", fr: "Dauphin", ar: "دلفين", tr: "Yunus", pl: "Delfin", uk: "Дельфін" } },
  { category: "CAT_ANIMALS", words: { fa: "نهنگ", en: "Whale", nl: "Walvis", de: "Wal", fr: "Baleine", ar: "حوت", tr: "Balina", pl: "Wieloryb", uk: "Кит" } },
  { category: "CAT_ANIMALS", words: { fa: "هشت‌پا", en: "Octopus", nl: "Octopus", de: "Oktopus", fr: "Poulpe", ar: "أخطبوط", tr: "Ahtapot", pl: "Ośmiornica", uk: "Восьминіг" } },
  { category: "CAT_ANIMALS", words: { fa: "حلزون", en: "Snail", nl: "Slak", de: "Schnecke", fr: "Escargot", ar: "حلزون", tr: "Salyangoz", pl: "Ślimak", uk: "Равлик" } },
  { category: "CAT_ANIMALS", words: { fa: "پروانه", en: "Butterfly", nl: "Vlinder", de: "Schmetterling", fr: "Papillon", ar: "فراشة", tr: "Kelebek", pl: "Motyl", uk: "Метелик" } },
  { category: "CAT_ANIMALS", words: { fa: "زنبور", en: "Bee", nl: "Bij", de: "Biene", fr: "Abeille", ar: "نحلة", tr: "Arı", pl: "Pszczoła", uk: "Бджола" } },
  { category: "CAT_ANIMALS", words: { fa: "مورچه", en: "Ant", nl: "Mier", de: "Ameise", fr: "Fourmi", ar: "نملة", tr: "Karınca", pl: "Mrówka", uk: "Мураха" } },
  { category: "CAT_ANIMALS", words: { fa: "سوسک", en: "Cockroach", nl: "Kakkerlak", de: "Kakerlake", fr: "Cafard", ar: "صرصور", tr: "Hamam böceği", pl: "Karaluch", uk: "Тарган" } },
  { category: "CAT_ANIMALS", words: { fa: "پشه", en: "Mosquito", nl: "Mug", de: "Mücke", fr: "Moustique", ar: "بعوضة", tr: "Sivrisinek", pl: "Komar", uk: "Комар" } },
  { category: "CAT_ANIMALS", words: { fa: "عنکبوت", en: "Spider", nl: "Spin", de: "Spinne", fr: "Araignée", ar: "عنكبوت", tr: "Örümcek", pl: "Pająk", uk: "Павук" } },
  { category: "CAT_ANIMALS", words: { fa: "پرنده", en: "Bird", nl: "Vogel", de: "Vogel", fr: "Oiseau", ar: "طائر", tr: "Kuş", pl: "Ptak", uk: "Птах" } },

  // 4. Jobs (CAT_JOBS)
  { category: "CAT_JOBS", words: { fa: "پزشک", en: "Doctor", nl: "Arts", de: "Arzt", fr: "Médecin", ar: "طبيب", tr: "Doktor", pl: "Lekarz", uk: "Лікар" } },
  { category: "CAT_JOBS", words: { fa: "پرستار", en: "Nurse", nl: "Verpleegster", de: "Krankenschwester", fr: "Infirmière", ar: "ممرضة", tr: "Hemşire", pl: "Pielęgniarka", uk: "Медсестра" } },
  { category: "CAT_JOBS", words: { fa: "معلم", en: "Teacher", nl: "Leraar", de: "Lehrer", fr: "Professeur", ar: "معلم", tr: "Öğretmen", pl: "Nauczyciel", uk: "Вчитель" } },
  { category: "CAT_JOBS", words: { fa: "مهندس", en: "Engineer", nl: "Ingenieur", de: "Ingenieur", fr: "Ingénieur", ar: "مهندس", tr: "Mühendis", pl: "Inżynier", uk: "Інженер" } },
  { category: "CAT_JOBS", words: { fa: "برنامه‌نویس", en: "Programmer", nl: "Programmeur", de: "Programmierer", fr: "Programmeur", ar: "مبرمج", tr: "Programcı", pl: "Programista", uk: "Програміст" } },
  { category: "CAT_JOBS", words: { fa: "آهنگر", en: "Blacksmith", nl: "Smid", de: "Schmied", fr: "Forgeron", ar: "حداد", tr: "Demirci", pl: "Kowal", uk: "Коваль" } },
  { category: "CAT_JOBS", words: { fa: "خلبان", en: "Pilot", nl: "Piloot", de: "Pilot", fr: "Pilote", ar: "طيار", tr: "Pilot", pl: "Pilot", uk: "Пілот" } },
  { category: "CAT_JOBS", words: { fa: "آشپز", en: "Chef", nl: "Kok", de: "Koch", fr: "Chef", ar: "طباخ", tr: "Aşçı", pl: "Kucharz", uk: "Кухар" } },
  { category: "CAT_JOBS", words: { fa: "پلیس", en: "Police", nl: "Politie", de: "Polizei", fr: "Police", ar: "شرطة", tr: "Polis", pl: "Policja", uk: "Поліція" } },
  { category: "CAT_JOBS", words: { fa: "سرباز", en: "Soldier", nl: "Soldaat", de: "Soldat", fr: "Soldat", ar: "جندي", tr: "Asker", pl: "Żołnierz", uk: "Солдат" } },
  { category: "CAT_JOBS", words: { fa: "آتش‌نشان", en: "Firefighter", nl: "Brandweerman", de: "Feuerwehrmann", fr: "Pompier", ar: "إطفائي", tr: "İtfaiyeci", pl: "Strażak", uk: "Пожежник" } },
  { category: "CAT_JOBS", words: { fa: "خبرنگار", en: "Journalist", nl: "Journalist", de: "Journalist", fr: "Journaliste", ar: "صحفي", tr: "Gazeteci", pl: "Dziennikarz", uk: "Журналіст" } },
  { category: "CAT_JOBS", words: { fa: "عکاس", en: "Photographer", nl: "Fotograaf", de: "Fotograf", fr: "Photographe", ar: "مصور", tr: "Fotoğrafçı", pl: "Fotograf", uk: "Фотограф" } },
  { category: "CAT_JOBS", words: { fa: "نویسنده", en: "Writer", nl: "Schrijver", de: "Autor", fr: "Écrivain", ar: "كاتب", tr: "Yazar", pl: "Pisarz", uk: "Письменник" } },
  { category: "CAT_JOBS", words: { fa: "مترجم", en: "Translator", nl: "Vertaler", de: "Übersetzer", fr: "Traducteur", ar: "مترجم", tr: "Tercüman", pl: "Tłumacz", uk: "Перекладач" } },

  // 5. Places (CAT_PLACES)
  { category: "CAT_PLACES", words: { fa: "آپارتمان", en: "Apartment", nl: "Appartement", de: "Wohnung", fr: "Appartement", ar: "شقة", tr: "Apartman", pl: "Mieszkanie", uk: "Квартира" } },
  { category: "CAT_PLACES", words: { fa: "ویلا", en: "Villa", nl: "Villa", de: "Villa", fr: "Villa", ar: "فيلا", tr: "Villa", pl: "Willa", uk: "Вілла" } },
  { category: "CAT_PLACES", words: { fa: "دانشگاه", en: "University", nl: "Universiteit", de: "Universität", fr: "Université", ar: "جامعة", tr: "Üniversite", pl: "Uniwersytet", uk: "Університет" } },
  { category: "CAT_PLACES", words: { fa: "کتابخانه", en: "Library", nl: "Bibliotheek", de: "Bibliothek", fr: "Bibliothèque", ar: "مكتبة", tr: "Kütüphane", pl: "Biblioteka", uk: "Бібліотека" } },
  { category: "CAT_PLACES", words: { fa: "آزمایشگاه", en: "Laboratory", nl: "Laboratorium", de: "Labor", fr: "Laboratoire", ar: "مختبر", tr: "Laboratuvar", pl: "Laboratorium", uk: "Лабораторія" } },
  { category: "CAT_PLACES", words: { fa: "بیمارستان", en: "Hospital", nl: "Ziekenhuis", de: "Krankenhaus", fr: "Hôpital", ar: "مستشفى", tr: "Hastane", pl: "Szpital", uk: "Лікарня" } },
  { category: "CAT_PLACES", words: { fa: "داروخانه", en: "Pharmacy", nl: "Apotheek", de: "Apotheke", fr: "Pharmacie", ar: "صيدلية", tr: "Eczane", pl: "Apteka", uk: "Аптека" } },
  { category: "CAT_PLACES", words: { fa: "سوپرمارکت", en: "Supermarket", nl: "Supermarkt", de: "Supermarkt", fr: "Supermarché", ar: "سوبر ماركت", tr: "Süpermarket", pl: "Supermarket", uk: "Супермаркет" } },
  { category: "CAT_PLACES", words: { fa: "بازار", en: "Market", nl: "Markt", de: "Markt", fr: "Marché", ar: "سوق", tr: "Pazar", pl: "Rynek", uk: "Ринок" } },
  { category: "CAT_PLACES", words: { fa: "رستوران", en: "Restaurant", nl: "Restaurant", de: "Restaurant", fr: "Restaurant", ar: "مطعم", tr: "Restoran", pl: "Restauracja", uk: "Ресторан" } },
  { category: "CAT_PLACES", words: { fa: "کافه", en: "Cafe", nl: "Cafe", de: "Cafe", fr: "Café", ar: "مقهى", tr: "Kafe", pl: "Kawiarnia", uk: "Кафе" } },
  { category: "CAT_PLACES", words: { fa: "سینما", en: "Cinema", nl: "Bioscoop", de: "Kino", fr: "Cinéma", ar: "سينما", tr: "Sinema", pl: "Kino", uk: "Кінотеатр" } },
  { category: "CAT_PLACES", words: { fa: "پارک", en: "Park", nl: "Park", de: "Park", fr: "Parc", ar: "منتزه", tr: "Park", pl: "Park", uk: "Парк" } },
  { category: "CAT_PLACES", words: { fa: "شهربازی", en: "Theme Park", nl: "Pretpark", de: "Freizeitpark", fr: "Parc d'attractions", ar: "مدينة ملاهي", tr: "Lunapark", pl: "Wesołe miasteczko", uk: "Парк розваг" } },
  { category: "CAT_PLACES", words: { fa: "باغ‌وحش", en: "Zoo", nl: "Dierentuin", de: "Zoo", fr: "Zoo", ar: "حديقة حيوان", tr: "Hayvanat bahçesi", pl: "ZOO", uk: "Зоопарк" } },
  { category: "CAT_PLACES", words: { fa: "موزه", en: "Museum", nl: "Museum", de: "Museum", fr: "Musée", ar: "متحف", tr: "Müze", pl: "Muzeum", uk: "Музей" } },
  { category: "CAT_PLACES", words: { fa: "ورزشگاه", en: "Stadium", nl: "Stadion", de: "Stadion", fr: "Stade", ar: "ملعب", tr: "Stadyum", pl: "Stadion", uk: "Стадіон" } },
  { category: "CAT_PLACES", words: { fa: "فرودگاه", en: "Airport", nl: "Luchthaven", de: "Flughafen", fr: "Aéroport", ar: "مطار", tr: "Havalimanı", pl: "Lotnisko", uk: "Аеропорт" } },
  { category: "CAT_PLACES", words: { fa: "هتل", en: "Hotel", nl: "Hotel", de: "Hotel", fr: "Hôtel", ar: "فندق", tr: "Otel", pl: "Hotel", uk: "Готель" } },
  { category: "CAT_PLACES", words: { fa: "بانک", en: "Bank", nl: "Bank", de: "Bank", fr: "Banque", ar: "بنك", tr: "Banka", pl: "Bank", uk: "Банк" } },
  { category: "CAT_PLACES", words: { fa: "جنگل", en: "Forest", nl: "Bos", de: "Wald", fr: "Forêt", ar: "غابة", tr: "Orman", pl: "Las", uk: "Ліс" } },
  { category: "CAT_PLACES", words: { fa: "کوه", en: "Mountain", nl: "Berg", de: "Berg", fr: "Montagne", ar: "جبل", tr: "Dağ", pl: "Góra", uk: "Гора" } },
  { category: "CAT_PLACES", words: { fa: "دریا", en: "Sea", nl: "Zee", de: "Meer", fr: "Mer", ar: "بحر", tr: "Deniz", pl: "Morze", uk: "Море" } },
  { category: "CAT_PLACES", words: { fa: "ساحل", en: "Beach", nl: "Strand", de: "Strand", fr: "Plage", ar: "شاطئ", tr: "Plaj", pl: "Plaża", uk: "Пляж" } },
  { category: "CAT_PLACES", words: { fa: "جزیره", en: "Island", nl: "Eiland", de: "Insel", fr: "Île", ar: "جزيرة", tr: "Ada", pl: "Wyspa", uk: "Острів" } },

  // 6. Vehicles (CAT_VEHICLES)
  { category: "CAT_VEHICLES", words: { fa: "ماشین", en: "Car", nl: "Auto", de: "Auto", fr: "Voiture", ar: "سيارة", tr: "Araba", pl: "Samochód", uk: "Машина" } },
  { category: "CAT_VEHICLES", words: { fa: "کامیون", en: "Truck", nl: "Vrachtwagen", de: "LKW", fr: "Camion", ar: "شاحنة", tr: "Kamyon", pl: "Ciężarówka", uk: "Вантажівка" } },
  { category: "CAT_VEHICLES", words: { fa: "اتوبوس", en: "Bus", nl: "Bus", de: "Bus", fr: "Bus", ar: "حافلة", tr: "Otobüs", pl: "Autobus", uk: "Автобус" } },
  { category: "CAT_VEHICLES", words: { fa: "تاکسی", en: "Taxi", nl: "Taxi", de: "Taxi", fr: "Taxi", ar: "تاكسي", tr: "Taksi", pl: "Taksówka", uk: "Таксі" } },
  { category: "CAT_VEHICLES", words: { fa: "موتورسیکلت", en: "Motorcycle", nl: "Motorfiets", de: "Motorrad", fr: "Moto", ar: "دراجة نارية", tr: "Motosiklet", pl: "Motocykl", uk: "Мотоцикл" } },
  { category: "CAT_VEHICLES", words: { fa: "دوچرخه", en: "Bicycle", nl: "Fiets", de: "Fahrrad", fr: "Vélo", ar: "دراجة", tr: "Bisiklet", pl: "Rower", uk: "Велосипед" } },
  { category: "CAT_VEHICLES", words: { fa: "قطار", en: "Train", nl: "Trein", de: "Zug", fr: "Train", ar: "قطار", tr: "Tren", pl: "Pociąg", uk: "Потяг" } },
  { category: "CAT_VEHICLES", words: { fa: "مترو", en: "Subway", nl: "Metro", de: "U-Bahn", fr: "Métro", ar: "مترو", tr: "Metro", pl: "Metro", uk: "Метро" } },
  { category: "CAT_VEHICLES", words: { fa: "هواپیما", en: "Airplane", nl: "Vliegtuig", de: "Flugzeug", fr: "Avion", ar: "طائرة", tr: "Uçak", pl: "Samolot", uk: "Літак" } },
  { category: "CAT_VEHICLES", words: { fa: "هلیکوپتر", en: "Helicopter", nl: "Helikopter", de: "Hubschrauber", fr: "Hélicoptère", ar: "مروحية", tr: "Helikopter", pl: "Helikopter", uk: "Гвинтокрил" } },
  { category: "CAT_VEHICLES", words: { fa: "کشتی", en: "Ship", nl: "Schip", de: "Schiff", fr: "Bateau", ar: "سفينة", tr: "Gemi", pl: "Statek", uk: "Корабель" } },
  { category: "CAT_VEHICLES", words: { fa: "قایق", en: "Boat", nl: "Boot", de: "Boot", fr: "Bateau", ar: "قارب", tr: "Tekne", pl: "Łódka", uk: "Човен" } },
  { category: "CAT_VEHICLES", words: { fa: "زیردریایی", en: "Submarine", nl: "Onderzeëer", de: "U-Boot", fr: "Sous-marin", ar: "غواصة", tr: "Denizaltı", pl: "Łódź podwodna", uk: "Підводний човен" } },
  { category: "CAT_VEHICLES", words: { fa: "آمبولانس", en: "Ambulance", nl: "Ambulance", de: "Krankenwagen", fr: "Ambulance", ar: "إسعاف", tr: "Ambulans", pl: "Ambulans", uk: "Швидка допомога" } },
  { category: "CAT_VEHICLES", words: { fa: "تراکتور", en: "Tractor", nl: "Tractor", de: "Traktor", fr: "Tracteur", ar: "جرار", tr: "Traktör", pl: "Traktor", uk: "Трактор" } },

  // 7. Feelings (CAT_FEELINGS)
  { category: "CAT_FEELINGS", words: { fa: "خوشحالی", en: "Happiness", nl: "Geluk", de: "Glück", fr: "Bonheur", ar: "سعادة", tr: "Mutluluk", pl: "Szczęście", uk: "Щастя" } },
  { category: "CAT_FEELINGS", words: { fa: "ناراحتی", en: "Sadness", nl: "Verdriet", de: "Trauer", fr: "Tristesse", ar: "حزن", tr: "Üzüntü", pl: "Smutek", uk: "Смуток" } },
  { category: "CAT_FEELINGS", words: { fa: "هیجان", en: "Excitement", nl: "Opwinding", de: "Aufregung", fr: "Excitation", ar: "حماس", tr: "Heyecan", pl: "Ekscytacja", uk: "Збудження" } },
  { category: "CAT_FEELINGS", words: { fa: "ترس", en: "Fear", nl: "Angst", de: "Angst", fr: "Peur", ar: "خوف", tr: "Korku", pl: "Strach", uk: "Жах" } },
  { category: "CAT_FEELINGS", words: { fa: "آرامش", en: "Calm", nl: "Rust", de: "Ruhe", fr: "Calme", ar: "هدوء", tr: "Sakinlik", pl: "Spój", uk: "Спокій" } },
  { category: "CAT_FEELINGS", words: { fa: "خشم", en: "Anger", nl: "Woede", de: "Wut", fr: "Colère", ar: "غضب", tr: "Öfke", pl: "Gniew", uk: "Гнів" } },
  { category: "CAT_FEELINGS", words: { fa: "عشق", en: "Love", nl: "Liefde", de: "Liebe", fr: "Amour", ar: "حب", tr: "Aşk", pl: "Miłość", uk: "Любов" } },
  { category: "CAT_FEELINGS", words: { fa: "حسادت", en: "Envy", nl: "Jaloezie", de: "Neid", fr: "Envie", ar: "حسد", tr: "Kıskançlık", pl: "Zazdrość", uk: "Заздрість" } },
  { category: "CAT_FEELINGS", words: { fa: "خجالت", en: "Shame", nl: "Schaamte", de: "Scham", fr: "Honte", ar: "خجل", tr: "Utanç", pl: "Wstyd", uk: "Сором" } },
  { category: "CAT_FEELINGS", words: { fa: "تعجب", en: "Surprise", nl: "Verrassing", de: "Überraschung", fr: "Surprise", ar: "مفاجأة", tr: "Sürpriz", pl: "Niespodzianka", uk: "Сюрприз" } },

  // 8. Sports & Games (CAT_SPORTS)
  { category: "CAT_SPORTS", words: { fa: "فوتبال", en: "Football", nl: "Voetbal", de: "Fußball", fr: "Football", ar: "كرة قدم", tr: "Futbol", pl: "Piłka nożna", uk: "Футбол" } },
  { category: "CAT_SPORTS", words: { fa: "بسکتبال", en: "Basketball", nl: "Basketbal", de: "Basketball", fr: "Basketball", ar: "كرة سلة", tr: "Basketbol", pl: "Koszykówka", uk: "Баскетбол" } },
  { category: "CAT_SPORTS", words: { fa: "والیبال", en: "Volleyball", nl: "Volleybal", de: "Volleyball", fr: "Volleyball", ar: "كرة طائرة", tr: "Voleybol", pl: "Siatkówka", uk: "Волейбол" } },
  { category: "CAT_SPORTS", words: { fa: "تنیس", en: "Tennis", nl: "Tennis", de: "Tennis", fr: "Tennis", ar: "تنس", tr: "Tenis", pl: "Tenis", uk: "Теніс" } },
  { category: "CAT_SPORTS", words: { fa: "شطرنج", en: "Chess", nl: "Schaken", de: "Schach", fr: "Échecs", ar: "شطرنج", tr: "Satranç", pl: "Szachy", uk: "Шахи" } },
  { category: "CAT_SPORTS", words: { fa: "شنا", en: "Swimming", nl: "Zwemmen", de: "Schwimmen", fr: "Natation", ar: "سباحة", tr: "Yüzme", pl: "Pływanie", uk: "Плавання" } },
  { category: "CAT_SPORTS", words: { fa: "بوکس", en: "Boxing", nl: "Boksen", de: "Boxen", fr: "Boxe", ar: "ملاكمة", tr: "Boks", pl: "Boks", uk: "Бокс" } },
  { category: "CAT_SPORTS", words: { fa: "کشتی", en: "Wrestling", nl: "Worstelen", de: "Ringen", fr: "Lutte", ar: "مصارعة", tr: "Güreş", pl: "Zapasy", uk: "Боротьба" } },

  // 9. Adjectives (CAT_ADJECTIVES)
  { category: "CAT_ADJECTIVES", words: { fa: "بزرگ", en: "Big", nl: "Groot", de: "Groß", fr: "Grand", ar: "كبير", tr: "Büyük", pl: "Duży", uk: "Великий" } },
  { category: "CAT_ADJECTIVES", words: { fa: "کوچک", en: "Small", nl: "Klein", de: "Klein", fr: "Petit", ar: "صغير", tr: "Küçük", pl: "Mały", uk: "Маленький" } },
  { category: "CAT_ADJECTIVES", words: { fa: "سریع", en: "Fast", nl: "Snel", de: "Schnell", fr: "Rapide", ar: "سريع", tr: "Hızlı", pl: "Szybki", uk: "Швидкий" } },
  { category: "CAT_ADJECTIVES", words: { fa: "سنگین", en: "Heavy", nl: "Zwaar", de: "Schwer", fr: "Lourd", ar: "ثقيل", tr: "Ağır", pl: "Ciężki", uk: "Важкий" } },
  { category: "CAT_ADJECTIVES", words: { fa: "گرم", en: "Hot", nl: "Heet", de: "Heiß", fr: "Chaud", ar: "ساخن", tr: "Sıcak", pl: "Gorący", uk: "Гарячий" } },
  { category: "CAT_ADJECTIVES", words: { fa: "سرد", en: "Cold", nl: "Koud", de: "Kalt", fr: "Froid", ar: "بارد", tr: "Soğuk", pl: "Zimny", uk: "Холодний" } },
  { category: "CAT_ADJECTIVES", words: { fa: "روشن", en: "Bright", nl: "Helder", de: "Hell", fr: "Clair", ar: "مضيء", tr: "Parlak", pl: "Jasny", uk: "Яскравий" } },
  { category: "CAT_ADJECTIVES", words: { fa: "کثیف", en: "Dirty", nl: "Vies", de: "Schmutzig", fr: "Sale", ar: "قذر", tr: "Kirli", pl: "Brudny", uk: "Брудний" } },
  { category: "CAT_ADJECTIVES", words: { fa: "آسان", en: "Easy", nl: "Makkelijk", de: "Einfach", fr: "Facile", ar: "سهل", tr: "Kolay", pl: "Łatwy", uk: "Легкий" } },
  { category: "CAT_ADJECTIVES", words: { fa: "سخت", en: "Hard", nl: "Moeilijk", de: "Schwer", fr: "Difficile", ar: "صعب", tr: "Zor", pl: "Trudny", uk: "Важкий" } },

  // 10. Entertainment (CAT_ENTERTAINMENT)
  { category: "CAT_ENTERTAINMENT", words: { fa: "فیلم", en: "Movie", nl: "Film", de: "Film", fr: "Film", ar: "فيلم", tr: "Film", pl: "Film", uk: "Фільм" } },
  { category: "CAT_ENTERTAINMENT", words: { fa: "سریال", en: "TV Series", nl: "Serie", de: "Serie", fr: "Série", ar: "مسلسل", tr: "Dizi", pl: "Serial", uk: "Серіал" } },
  { category: "CAT_ENTERTAINMENT", words: { fa: "انیمیشن", en: "Animation", nl: "Animatie", de: "Animation", fr: "Animation", ar: "رسوم متحركة", tr: "Animasyon", pl: "Animacja", uk: "Анімація" } },
  { category: "CAT_ENTERTAINMENT", words: { fa: "داستان", en: "Story", nl: "Verhaal", de: "Geschichte", fr: "Histoire", ar: "قصة", tr: "Hikaye", pl: "Opowieść", uk: "Історія" } },
  { category: "CAT_ENTERTAINMENT", words: { fa: "قهرمان", en: "Hero", nl: "Held", de: "Held", fr: "Héros", ar: "بطل", tr: "Kahraman", pl: "Bohater", uk: "Герой" } },
  { category: "CAT_ENTERTAINMENT", words: { fa: "راز", en: "Secret", nl: "Geheim", de: "Geheimnis", fr: "Secret", ar: "سر", tr: "Gizem", pl: "Tajemnica", uk: "Таємниця" } }
];
